#ifndef __MODULE__SDLKEYCODES_HPP__
#define __MODULE__SDLKEYCODES_HPP__

#include <KeyCodes.hpp>

namespace Module {
	KeyCode::Code lowLookup[] {
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Backspace,
		KeyCode::Tab,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Enter,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Escape,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Space,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Apostrophe,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Comma,
		KeyCode::Dash,
		KeyCode::Period,
		KeyCode::Slash,
		KeyCode::Key0,
		KeyCode::Key1,
		KeyCode::Key2,
		KeyCode::Key3,
		KeyCode::Key4,
		KeyCode::Key5,
		KeyCode::Key6,
		KeyCode::Key7,
		KeyCode::Key8,
		KeyCode::Key9,
		KeyCode::Invalid,
		KeyCode::Semicolon,
		KeyCode::Invalid,
		KeyCode::Equals,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::LeftBracket,
		KeyCode::Backslash,
		KeyCode::RightBracket,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Grave,
		KeyCode::A,
		KeyCode::B,
		KeyCode::C,
		KeyCode::D,
		KeyCode::E,
		KeyCode::F,
		KeyCode::G,
		KeyCode::H,
		KeyCode::I,
		KeyCode::J,
		KeyCode::K,
		KeyCode::L,
		KeyCode::M,
		KeyCode::N,
		KeyCode::O,
		KeyCode::P,
		KeyCode::Q,
		KeyCode::R,
		KeyCode::S,
		KeyCode::T,
		KeyCode::U,
		KeyCode::V,
		KeyCode::W,
		KeyCode::X,
		KeyCode::Y,
		KeyCode::Z,
		KeyCode::Del		
	};
	
	KeyCode::Code highLookup[] {
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::CapsLock,
		KeyCode::F1,
		KeyCode::F2,
		KeyCode::F3,
		KeyCode::F4,
		KeyCode::F5,
		KeyCode::F6,
		KeyCode::F7,
		KeyCode::F8,
		KeyCode::F9,
		KeyCode::F10,
		KeyCode::F11,
		KeyCode::F12,
		KeyCode::Invalid, //PrintScreen
		KeyCode::Invalid, //ScrollLock
		KeyCode::Pause,
		KeyCode::Insert,
		KeyCode::Home,
		KeyCode::PageUp,
		KeyCode::Invalid,
		KeyCode::End,
		KeyCode::PageDown,
		KeyCode::Right,
		KeyCode::Left,
		KeyCode::Down,
		KeyCode::Up,
		KeyCode::Invalid,
		KeyCode::Invalid, //Numpad Divide
		KeyCode::Invalid, //Numpad Multiply
		KeyCode::Invalid, //Numpad Minus
		KeyCode::Invalid, //Numpad Plus
		KeyCode::Invalid, //Numpad Enter
		KeyCode::Numpad1,
		KeyCode::Numpad2,
		KeyCode::Numpad3,
		KeyCode::Numpad4,
		KeyCode::Numpad5,
		KeyCode::Numpad6,
		KeyCode::Numpad7,
		KeyCode::Numpad8,
		KeyCode::Numpad9,
		KeyCode::Numpad0,
		KeyCode::Invalid, //Numpad Period
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //Numpad Equals
		KeyCode::Invalid, //F13
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //F24
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //Volume up
		KeyCode::Invalid, //Volume down
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //Numpad comma
		KeyCode::Invalid, //Numpad EqualsAS40?
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //Clear
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //Numpad left paren
		KeyCode::Invalid, //Numpad right paren
		KeyCode::Invalid, //Numpad left brace
		KeyCode::Invalid, //Numpad right brace
		KeyCode::Invalid, //Numpad tab
		KeyCode::Invalid, //Numpad backspace
		KeyCode::Invalid, //Numpad A
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //Numpad F
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid, //Numpad less
		KeyCode::Invalid, //Numpad greater
		KeyCode::Invalid, //Numpad ampersand
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Ctrl, //Left
		KeyCode::Shift, //Left
		KeyCode::Alt, //Left
		KeyCode::Invalid,
		KeyCode::Ctrl, //Right
		KeyCode::Shift, //Right
		KeyCode::Alt, //Right
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
		KeyCode::Invalid,
	};
	
	KeyCode::Code getKeyCode(SDL_Keycode sym);
	uint8_t getChar(SDL_Keycode sym, uint16_t mod);
}

#endif